server:
  port: 8087
  address: 0.0.0.0
  forward-headers-strategy: framework

  servlet:
    context-path: /api

spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

      chat:
        options:
          model: ${AI_MODEL:llama3:latest}

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_DATABASE}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

  cache:
    type: redis

ai:
  provider: ${AI_PROVIDER:ollama}
  model: ${AI_MODEL:llama3:latest}

  prompt:
    activation-retry:
      max-attempts: 3
      initial-delay: 50ms
      multiplier: 2.0
      max-delay: 300ms

cache:
  default-ttl: 30m

  active-prompt:
    ttl: 1h

request-id:
  prefix: ${REQUEST_ID_PREFIX:request-id:}
  ttl: ${REQUEST_ID_TTL:30s}
  value: ${AI_SERVICE_REQUEST_ID_VALUE:ai-service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: host.docker.internal
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true