server:
  port: 8087
  forward-headers-strategy: framework
  servlet:
    context-path: /api
#spring:
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: gpt-4o-mini

spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        options:
          model: ${OLLAMA_MODEL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
#    enabled: false  # Swagger UI отображается только через gateway