server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  access-secret: ${ACCESS_SECRET}
  refresh-secret: ${REFRESH_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
