server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    discovery:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000
            loggerLevel: full
          user-service:
            connect-timeout: 1500
            read-timeout: 2500

jwt:
  access-secret: ${ACCESS_SECRET}
  refresh-secret: ${REFRESH_SECRET}
  access-token-expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS}
  cookie-path: ${COOKIE_PATH}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always